### ISSUE TITLE
Didn't called closure on 'setActiveIdentifier'

### ISSUE THREAD

**Issue by p-x9** [emptygalaxy/homebridge-http-television#2]
It seems that the following closure[InputSourceHandler.ts#L137](https://github.com/emptygalaxy/homebridge-http-television/blob/master/src/InputSourceHandler.ts#L137) part in this function ([InputSourceHandler.ts#L130](https://github.com/emptygalaxy/homebridge-http-television/blob/master/src/InputSourceHandler.ts#L130)) is not being called.

**Comment by p-x9** [comment]
I think that this issue is related to another package 'http-television'

**Comment by emptygalaxy** [comment]
Good find, I've issued a patch and updated the plugin too now.
Please check version 0.0.4.

**Comment by p-x9** [comment]
Thanks.
I’ve confirmed that it works correctly with version 0.04.
